version: 2.1

orbs:
  advanced-checkout-beta: vsco/advanced-checkout@dev:beta
  orb-tools: circleci/orb-tools@9.3.1

var_1: &no_main_filter
  filters:
    branches:
      ignore:
        - main

var_2: &main_filter
  filters:
    branches:
      only:
        - main

workflows:
  build:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          name: alpha publish
          <<: *no_main_filter
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: 'dev:alpha'
          orb-name: vsco/advanced-checkout
      - orb-tools/publish-dev:
          name: beta publish
          <<: *main_filter
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: 'dev:beta'
          orb-name: vsco/advanced-checkout
  integration-tests:
    jobs:
      - orb-tools/pack:
          name: pack-dev
      - orb-tools/test-in-builds:
          name: test-dev
          attach-workspace: true
          orb-name: advanced-checkout
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: src/tests/shallow_checkout_default.yml
            - orb-tools/local-test-build:
                test-config-location: src/tests/shallow_checkout_full.yml
            - orb-tools/local-test-build:
                test-config-location: src/tests/shallow_checkout_working_path.yml
          requires:
            - pack-dev
