version: 2.1

orbs:
  advanced-checkout: vsco/advanced-checkout@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0.0

# Pipeline Parameters
parameters:
  dev-orb-version:
    description: >
      The development version of the orb to test.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

var_1: &main_branch_filter
  filters:
    branches:
      ignore:
        - main
        - master

workflows:
  build-and-test:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          requires:
            - orb-tools/lint
            - orb-tools/pack
          orb-name: vsco/advanced-checkout
