version: 2.1

orbs:
  advanced-checkout-alpha: vsco/advanced-checkout@dev:alpha
  advanced-checkout-beta: vsco/advanced-checkout@dev:beta
  orb-tools: circleci/orb-tools@10.0.0

var_1: &default_job_setup
  docker:
    - image: 'cimg/base:2020.01'
  resource_class: small

var_2: &no_main_filter
  filters:
    branches:
      ignore:
        - main

var_3: &main_filter
  filters:
    branches:
      only:
        - main

jobs:
  advanced-shallow-checkout-alpha:
    <<: *default_job_setup
    steps:
      - advanced-checkout-alpha/shallow-checkout
      - run:
          name: ensure the checkout succeeded from dev:alpha
          command: find src/@orb.yml
  advanced-shallow-checkout-beta:
    <<: *default_job_setup
    steps:
      - advanced-checkout-beta/shallow-checkout
      - run:
          name: ensure the checkout succeeded from dev:beta
          command: find src/@orb.yml

workflows:
  build-and-test:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          name: alpha publish
          <<: *no_main_filter
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: 'dev:alpha'
          orb-name: vsco/advanced-checkout
      - advanced-shallow-checkout-alpha:
          name: test published dev:alpha orb
          <<: *no_main_filter
          requires:
            - alpha publish
      - orb-tools/publish-dev:
          name: beta publish
          <<: *main_filter
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: 'dev:beta'
          orb-name: vsco/advanced-checkout
      - advanced-shallow-checkout-beta:
          name: test published dev:beta orb
          <<: *main_filter
          requires:
            - beta publish
