version: 2.1

orbs:
  advanced-checkout-alpha: vsco/advanced-checkout@dev:alpha
  advanced-checkout-beta: vsco/advanced-checkout@dev:beta
  orb-tools: circleci/orb-tools@10.0.0

var_1: &default_job_setup
  docker:
    - image: 'circleci/circleci-cli:latest'
  resource_class: small

var_2: &no_main_filter
  filters:
    branches:
      ignore:
        - main

var_3: &main_filter
  filters:
    branches:
      only:
        - main

jobs:
  advanced-shallow-checkout-alpha:
    <<: *default_job_setup
    steps:
      - advanced-checkout-alpha/shallow-checkout
      - run:
          command: find .
  advanced-shallow-checkout-beta:
    <<: *default_job_setup
    steps:
      - advanced-checkout-beta/shallow-checkout
      - run:
          command: find .

workflows:
  build-and-test:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          <<: *no_main_filter
          name: alpha publish
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: "dev:alpha"
          orb-name: vsco/advanced-checkout
      - advanced-shallow-checkout-alpha:
          <<: *no_main_filter
          requires:
            - alpha publish
      - orb-tools/publish-dev:
          <<: *main_filter
          name: beta publish
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: "dev:alpha"
          orb-name: vsco/advanced-checkout
      - advanced-shallow-checkout-beta:
          <<: *main_filter
          requires:
            - beta publish
