version: 2.1

orbs:
  advanced-checkout-beta: vsco/advanced-checkout@dev:beta
  orb-tools: circleci/orb-tools@9.3.1
  test:
    orbs:
      orb-tools: circleci/orb-tools@9.3.1
    # Workaround for passing a SSH key with orb-tools/local-test-build command
    # https://github.com/CircleCI-Public/orb-tools-orb/blob/v9.3.1/src/commands/local-test-build.yml
    commands:
      local-test-build:
        parameters:
          test-config-location:
            description: >
              Location of a the test config file. This looks like a regular config,
              but it will have the orb being tested added as a local orb,
              with the orb name that is passed into the test-in-builds job this belongs to.
            type: string
          external-check-steps:
            description: >
              Checks you want to run that look at the contents of local_build_output.txt.
              Checks that depend on the environment inside the test job should go inside the test config.
              This step should probably call a script rather than hardcode the checks into your config.
            type: steps
            default: []
        steps:
          - run: mkdir -p tmp-config-src
          - run: cp << parameters.test-config-location >> tmp-config-src/config.yml
          - orb-tools/pack:
              source: tmp-config-src
              destination: uncompiled-config.yml
          # run that uncompiled-config inside a local job - it will have pre-steps that contain the config to be packed inside it, and post-steps that check that it looks like it should
          - run: cat uncompiled-config.yml
          - run:
              name: compile test config
              command: circleci config process --skip-update-check uncompiled-config.yml > config.yml
          - run:
              name: run test job locally
              command: |
                # Cannot access "~/.ssh" from working directory.
                cp ~/.ssh/id_rsa ./id_rsa
                circleci local execute --checkout-key ./id_rsa -c config.yml | \
                  tee local_build_output.txt /dev/stderr | \
                  tail -n 1 | \
                  grep "Success"
          - << parameters.external-check-steps >>

var_1: &no_main_filter
  filters:
    branches:
      ignore:
        - main

var_2: &main_filter
  filters:
    branches:
      only:
        - main

workflows:
  build:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          name: alpha publish
          <<: *no_main_filter
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: 'dev:alpha'
          orb-name: vsco/advanced-checkout
      - orb-tools/publish-dev:
          name: beta publish
          <<: *main_filter
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: 'dev:beta'
          orb-name: vsco/advanced-checkout
  integration-tests:
    jobs:
      - orb-tools/pack:
          name: pack-dev
          <<: *no_main_filter
      - orb-tools/test-in-builds:
          name: test-dev default
          <<: *no_main_filter
          attach-workspace: true
          orb-name: advanced-checkout
          test-steps:
            - test/local-test-build:
                test-config-location: src/tests/default_shallow_checkout.yml
            - test/local-test-build:
                test-config-location: src/tests/default_shallow_checkout_full.yml
            - test/local-test-build:
                test-config-location: src/tests/default_shallow_checkout_working_path.yml
          requires:
            - pack-dev
      - orb-tools/test-in-builds:
          name: test-dev android
          <<: *no_main_filter
          attach-workspace: true
          orb-name: advanced-checkout
          test-steps:
            - test/local-test-build:
                test-config-location: src/tests/android_shallow_checkout.yml
            - test/local-test-build:
                test-config-location: src/tests/android_shallow_checkout_full.yml
            - test/local-test-build:
                test-config-location: src/tests/android_shallow_checkout_working_path.yml
          requires:
            - pack-dev
