version: 2.1

orbs:
  advanced-checkout-alpha: vsco/advanced-checkout@dev:alpha
  advanced-checkout-beta: vsco/advanced-checkout@dev:beta
  orb-tools: circleci/orb-tools@10.0.0

var_1: &default_job_setup
  docker:
    - image: 'circleci/circleci-cli:latest'
  resource_class: small

jobs:
  build-and-test-alpha:
    <<: *default_job_setup
    steps:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: "dev:alpha"
          orb-name: vsco/advanced-checkout
      - advanced-checkout-alpha
      - command:
          run: find .
  build-and-test-beta:
    <<: *default_job_setup
    steps:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          requires:
            - orb-tools/lint
            - orb-tools/pack
          alpha-version-ref: "dev:beta"
          orb-name: vsco/advanced-checkout
      - advanced-checkout-beta
      - command:
          run: find .
workflows:
  build-and-test-alpha:
    jobs:
      - build-and-test-alpha:
          filters:
            branches:
              ignore:
                - main
                - master
  build-and-test-beta:
    jobs:
      - build-and-test-beta:
          filters:
            branches:
              only:
                - main
